-- MySQL Script generated by MySQL Workbench
-- Wed Oct 29 10:09:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema event_hive
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema event_hive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `event_hive` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `event_hive` ;

-- -----------------------------------------------------
-- Table `event_hive`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_hive`.`users` (
  `user_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `password_hash` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_hive`.`attendees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_hive`.`attendees` (
  `attendee_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `user_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`attendee_id`),
  INDEX `fk_attendee_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_attendee_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `event_hive`.`users` (`user_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_hive`.`hive_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_hive`.`hive_events` (
  `event_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `location` VARCHAR(255) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `capacity` INT NOT NULL,
  `created_by` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`event_id`),
  INDEX `idx_events_start_time` (`start_time` ASC) VISIBLE,
  INDEX `idx_events_creator` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_event_creator`
    FOREIGN KEY (`created_by`)
    REFERENCES `event_hive`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_hive`.`rsvps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_hive`.`rsvps` (
  `rsvp_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` BIGINT UNSIGNED NOT NULL,
  `attendee_id` BIGINT UNSIGNED NOT NULL,
  `rsvp_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(20) NULL DEFAULT 'confirmed',
  PRIMARY KEY (`rsvp_id`),
  UNIQUE INDEX `unique_rsvp` (`event_id` ASC, `attendee_id` ASC) VISIBLE,
  INDEX `fk_rsvp_attendee` (`attendee_id` ASC) VISIBLE,
  CONSTRAINT `fk_rsvp_attendee`
    FOREIGN KEY (`attendee_id`)
    REFERENCES `event_hive`.`attendees` (`attendee_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_rsvp_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `event_hive`.`hive_events` (`event_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `event_hive` ;

-- -----------------------------------------------------
-- Placeholder table for view `event_hive`.`user_dashboard_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_hive`.`user_dashboard_view` (`user_id` INT, `event_id` INT, `title` INT, `start_time` INT, `location` INT, `status` INT, `rsvp_time` INT);

-- -----------------------------------------------------
-- View `event_hive`.`user_dashboard_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_hive`.`user_dashboard_view`;
USE `event_hive`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `event_hive`.`user_dashboard_view` AS select `u`.`user_id` AS `user_id`,`e`.`event_id` AS `event_id`,`e`.`title` AS `title`,`e`.`start_time` AS `start_time`,`e`.`location` AS `location`,`r`.`status` AS `status`,`r`.`rsvp_time` AS `rsvp_time` from (((`event_hive`.`users` `u` join `event_hive`.`attendees` `a` on((`u`.`user_id` = `a`.`user_id`))) join `event_hive`.`rsvps` `r` on((`a`.`attendee_id` = `r`.`attendee_id`))) join `event_hive`.`hive_events` `e` on((`r`.`event_id` = `e`.`event_id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
