""" the final db

Revision ID: 35fb6dbff86c
Revises: 4456e188433d
Create Date: 2025-11-14 22:17:38.476934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fb6dbff86c'
down_revision = '4456e188433d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starttime', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('endtime', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Enum('WORKSHOP', 'SEMINAR', 'MEETING', 'CONFERENCE', 'PARTY', 'CELEBRATION', 'NETWORKING', 'FUNDRAISER', 'COMPETITION', 'PERFORMANCE', 'FESTIVAL', 'WEBINAR', 'TRAINING', 'SPORTS', 'TRIP', 'VOLUNTEERING', 'HACKATHON', 'LAUNCH', 'CULTURAL', 'EDUCATIONAL', 'ENTERTAINMENT', 'SOCIAL', 'PROFESSIONAL', 'TECH', 'ART', 'MUSIC', 'FOOD', 'HEALTH', 'ENVIRONMENT', name='eventtag'), nullable=False))
        batch_op.alter_column('time',
               existing_type=sa.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.drop_column('tags')
        batch_op.drop_column('endtime')
        batch_op.drop_column('starttime')

    # ### end Alembic commands ###
