"""Initial migration - all tables

Revision ID: a8aed9e777e9
Revises: 
Create Date: 2025-11-19 02:12:24.370545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8aed9e777e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('starttime', sa.Time(), nullable=True),
    sa.Column('endtime', sa.Time(), nullable=True),
    sa.Column('mode', sa.Enum('online', 'offline', name='eventmode'), nullable=False),
    sa.Column('venue', sa.String(length=150), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Enum('WORKSHOP', 'SEMINAR', 'MEETING', 'CONFERENCE', 'PARTY', 'CELEBRATION', 'NETWORKING', 'FUNDRAISER', 'COMPETITION', 'PERFORMANCE', 'FESTIVAL', 'WEBINAR', 'TRAINING', 'SPORTS', 'TRIP', 'VOLUNTEERING', 'HACKATHON', 'LAUNCH', 'CULTURAL', 'EDUCATIONAL', 'ENTERTAINMENT', 'SOCIAL', 'PROFESSIONAL', 'TECH', 'ART', 'MUSIC', 'FOOD', 'HEALTH', 'ENVIRONMENT', name='eventtag'), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'private', name='eventvisibility'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('qr_code_path', sa.String(length=255), nullable=True),
    sa.Column('has_attended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('event_attendees',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.create_table('event_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join_requests')
    op.drop_table('event_notification')
    op.drop_table('event_attendees')
    op.drop_table('attendees')
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
